server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      host: 192.168.132.134
      database: xc_cms
  rabbitmq:
    host: 192.168.132.134
    port: 5672
    username: guest
    password: guest
    virtualHost: /